# Generated by Django 4.2.4 on 2023-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_social_link',
            old_name='portfolio',
            new_name='websit',
        ),
        migrations.AddField(
            model_name='user_social_link',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
